layout_spectrum: 0.15773106976227816
typography_spectrum: 0.5693058423959826
color:
  lightness: 0.5803718049011866
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#C01616'
    - '#A5A5A5'
    - '#FED52E'
  saturation: 0.21881641281372174
  brandStrength: 0.18896284108206923
  rhythmicContrast: 0.0039100550059782396
content_rating:
  adult: false
github: true
opengraph: {}
analytics:
  google: UA-64070424-1
author:
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
  name: The Film Dream
name: The Film Dream Academy
url: 'https://thegrid.ai/thefilmdreamacademy/'
navigation:
  - name: About us
    id: a6d4f0bf-181a-4cda-ad38-82587aa385c8
    type: content
  - name: Indie 101
    id: 0a3413a1-00b7-4086-9406-2cb545066de3
    type: content
  - name: Spotlight
    id: 5a15cb91-ee5a-4a28-b224-6c4f0f010adb
    type: content
  - name: News & Festivals
    id: 8f11bbc1-2a04-4175-a691-267947b7bf39
    type: content
  - name: Filmmakers' Society
    id: 3c730bc7-ae1e-480e-bcc0-35483336c5a8
    type: content
  - name: Masterclass
    id: d1495fa5-9495-426c-974b-8c246a8fe916
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Of Life Stories and Inspiring Filmmakers
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a754d2e-3cc2-4994-8f46-7abae99b8be2.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a754d2e-3cc2-4994-8f46-7abae99b8be2.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Unleash the Storyteller Within You!
purpose:
  - type: external
    url: 'http://thefilmdream.com'
    label: 'http://thefilmdream.com'
  - type: contact
    url: 'mailto:thefilmdream@icloud.com'
    label: Let's collaborate!
