name: TFD Academy
analytics:
  google: UA-64070424-1
github: true
description: Unleash the Storyteller in you!
author:
  url: 'http://thefilmdream.com'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.5337044359184802
color:
  lightness: 0.6110481071777288
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  saturation: 0.1259706609710051
  brandStrength: 0.5054697248864616
  rhythmicContrast: 0.7675158366950964
content_rating:
  adult: false
typography_spectrum: 0.6341172032989562
opengraph: {}
title: TFD Academy
