name: The Film Dream Academy
analytics:
  google: UA-64070424-1
purpose:
  - type: external
    url: 'http://thefilmdream.com'
    label: 'http://thefilmdream.com'
  - type: contact
    url: 'mailto:thefilmdream@icloud.com'
    label: Let's collaborate!
github: true
description: Unleash the Storyteller Within You!
author:
  name: The Film Dream
  url: 'http://www.thefilmdream.com'
  email: thefilmdream@icloud.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
navigation:
  - name: About us
    id: a6d4f0bf-181a-4cda-ad38-82587aa385c8
    type: content
  - name: Spotlight
    id: 5cd0fa33-4eac-43c2-8c93-1458332b7332
    type: content
  - name: Indie 101
    id: 1708e7ec-c485-4578-a381-02b522942b8f
    type: content
layout_spectrum: 0.15773106976227816
color:
  lightness: 0.5803718049011866
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#C01616'
    - '#A5A5A5'
    - '#FED52E'
  saturation: 0.21881641281372174
  brandStrength: 0.18896284108206923
  rhythmicContrast: 0.0039100550059782396
content_rating:
  adult: false
typography_spectrum: 0.5693058423959826
opengraph: {}
title: The Film Dream Academy
url: 'http://thefilmdreamacademy.com'
