typography_spectrum: 0.6341172032989562
content_rating:
  adult: false
color:
  lightness: 0.6110481071777288
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  saturation: 0.1259706609710051
  brandStrength: 0.5054697248864616
  rhythmicContrast: 0.7675158366950964
github: true
opengraph: {}
layout_spectrum: 0.5337044359184802
analytics:
  google: UA-64070424-1
author:
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
  name: The Film Dream
name: The Film Dream Academy
url: 'https://thegrid.ai/thefilmdreamacademy/'
navigation:
  - name: About us
    id: a6d4f0bf-181a-4cda-ad38-82587aa385c8
    type: content
  - name: Indie 101
    id: 0a3413a1-00b7-4086-9406-2cb545066de3
    type: content
  - name: Spotlight
    id: 5a15cb91-ee5a-4a28-b224-6c4f0f010adb
    type: content
  - name: News & Festivals
    id: 8f11bbc1-2a04-4175-a691-267947b7bf39
    type: content
  - name: Filmmakers' Society
    id: 3c730bc7-ae1e-480e-bcc0-35483336c5a8
    type: content
  - name: Masterclass
    id: d1495fa5-9495-426c-974b-8c246a8fe916
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Film Dream Academy
content: []
description: Unleash the Storyteller Within You!
purpose:
  - type: contact
    url: 'mailto:thefilmdream@icloud.com'
    label: Powered by thefilmdream.com
